const STARTER_AVATARS = ['🗑️', '🦝', '🛒', '🔦', '⚙️', '📦'];

export const normalizeUsernameBase = (value: string) => {
  const normalized = value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '')
    .slice(0, 18);

  return normalized || 'scavenger';
};

export const pickStarterAvatar = (seed: string) => {
  const sum = seed.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
  return STARTER_AVATARS[sum % STARTER_AVATARS.length];
};

export const createStarterProfileData = (displayName: string) => ({
  displayName,
  avatar: pickStarterAvatar(displayName),
  rank: 1,
  reputation: 0,
  cash: 250,
  heat: 0,
  energy: 100,
  maxEnergy: 100,
  inventoryCapacity: 100,
  usedCapacity: 0,
  currentDistrict: 'slums',
  currentPage: 'city',
  totalScavenged: 0,
  inventoryJson: '[]',
  equipmentJson: JSON.stringify({
    cart: null,
    backpack: null,
    flashlight: null,
    gloves: null,
  }),
  settingsJson: JSON.stringify({
    tutorialSeen: false,
    notifications: true,
    theme: 'neon',
    itemsFound: 0,
    sessionStreak: 1,
    lastActiveDate: null,
    marketCycle: 0,
    marketListings: [],
    auctionListings: [],
    directTradeOffers: [],
    junkyardStorage: [],
    junkyardJobs: [],
    junkyardWorkers: [],
    junkyardApplicants: [],
    junkyardFacilities: [],
    junkyardStats: {
      lifetimeMaterialsProcessed: 0,
      lifetimeJobsCompleted: 0,
      activeDays: 0,
      lastProcessedDay: null,
    },
    upgradeTreeProgress: {
      transport: null,
      equipment: null,
      lighting: null,
      storage: null,
    },
    progressionHoursPlayed: 0,
    maxParallelJobs: 3,
    maxWorkerSlots: 3,
    tradeHistory: [],
    missions: [],
    missionStats: {
      districtVisits: { slums: 0, tech: 0, financial: 0, harbor: 0, university: 0, rich_hills: 0 },
      pageVisits: { city: 0, inventory: 0, market: 0, junkyard: 0, upgrades: 0, missions: 0, guild: 0, settings: 0 },
      scavengeBuckets: {},
      interactionCounts: { buy_market: 0, sell_market: 0, purchase_upgrade: 0, accept_mission: 0, claim_mission: 0 },
      recycledWeightByCategory: { Electronics: 0, Metals: 0, Software: 0, Waste: 0 },
      recycledWeightTotal: 0,
    },
    factionStandings: { scavengers: 0, corp: 0, gangs: 0, police: 0, neutrals: 0 },
    factionRewardHistory: [],
    travel: {
      status: 'idle',
      mode: null,
      origin: 'slums',
      destination: null,
      departureAt: null,
      arrivalAt: null,
      fareCost: 0,
      cargoCapacity: 0,
      durationMs: 0,
    },
    property: {
      activePropertyId: 'starter-dumpster',
      shackAccess: {
        unlocked: false,
        completedAt: null,
      },
      properties: [
        {
          id: 'starter-dumpster',
          name: `${displayName}'s Dumpster`,
          district: 'slums',
          tier: 'dumpster',
          occupancyStatus: 'active',
          storageCapacity: 25,
          assemblyTier: 0,
          canDisassemble: false,
          canRecycle: false,
          employeeCapacity: 0,
          storageUpgradeLevel: 0,
          storedItems: [],
          letting: null,
        },
      ],
    },
    guild: {
      membershipStatus: 'none',
      id: null,
      name: '',
      tag: '',
      joinMode: 'application',
      level: 1,
      treasury: 0,
      treasuryCapacity: 10000,
      prestige: 0,
      memberSlots: 12,
      taxRate: 0.04,
      guildHallUnlocked: false,
      territory: [],
      upgrades: { treasury_capacity: 0, training_grounds: 0, vault_security: 0 },
      permissionsByRole: {
        owner: ['manage_members', 'withdraw_treasury', 'manage_settings', 'start_wars', 'manage_bulletin', 'manage_vault'],
        officer: ['manage_members', 'manage_bulletin', 'manage_vault'],
        member: [],
      },
      members: [],
      activityLog: [],
      chatMessages: [],
      bulletinPosts: [],
      vault: [],
      weeklyQuest: {
        id: 'guild-quest-starter',
        title: 'District Cleanup Push',
        description: 'Push the guild through scavenged value and recycling output before Sunday reset.',
        scavengedValueTarget: 2200,
        scavengedValueProgress: 0,
        recycledWeightTarget: 110,
        recycledWeightProgress: 0,
        rewardCash: 2800,
        rewardPrestige: 14,
        status: 'active',
        resetsAt: 0,
      },
      war: {
        status: 'peace',
        opponent: null,
        declaredAt: null,
        occupationEndsAt: null,
        cooldownEndsAt: null,
        targetDistricts: [],
        rewardBonusUntil: null,
        penaltyUntil: null,
        lastResult: null,
      },
      availableGuilds: [],
      lastMaintenanceAt: 0,
    },
    lastMissionRefreshAt: 0,
    ownedVehicles: {},
  }),
});
