export type LootRarity = 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary' | 'illegal';

export interface LootTemplate {
  id: string;
  name: string;
  icon: string;
  rarity: LootRarity;
  quantity: number;
  weight: number;
  value: number;
  description: string;
}

type LootSeed = readonly [id: string, name: string, icon: string, weight: number, value: number, description: string];

const createLootItems = (rarity: LootRarity, items: LootSeed[]): LootTemplate[] =>
  items.map(([id, name, icon, weight, value, description]) => ({
    id,
    name,
    icon,
    rarity,
    quantity: 1,
    weight,
    value,
    description,
  }));

export const LOOT_TEMPLATES: Record<LootRarity, LootTemplate[]> = {
  common: [
    { id: 'c1', name: 'Copper Wire', icon: '🔌', rarity: 'common', quantity: 1, weight: 0.5, value: 15, description: 'Stripped wiring.' },
    { id: 'c2', name: 'Steel Scrap', icon: '⚙️', rarity: 'common', quantity: 1, weight: 2.0, value: 8, description: 'Bent metal plates.' },
    { id: 'c3', name: 'Empty Cans', icon: '🥫', rarity: 'common', quantity: 1, weight: 0.2, value: 3, description: 'Recyclable tin cans.' },
    { id: 'c4', name: 'Plastic Bottles', icon: '🍾', rarity: 'common', quantity: 1, weight: 0.1, value: 2, description: 'Various plastic containers.' },
    { id: 'c5', name: 'Corroded Battery', icon: '🔋', rarity: 'common', quantity: 1, weight: 0.3, value: 5, description: 'Still has trace charge.' },
    { id: 'cons_soda', name: 'Soda', icon: '🥤', rarity: 'common', quantity: 1, weight: 0.4, value: 12, description: 'Quick sugar boost. Restores 12 energy.' },
    ...createLootItems('common', [
      ['c6', 'Burnt Charger', '🔌', 0.2, 9, 'Heat-warped phone charger pulled from a dorm dumpster.'],
      ['c7', 'Cracked Webcam', '📷', 0.3, 11, 'Lens is chipped but the board still powers on.'],
      ['c8', 'Frayed Earbuds', '🎧', 0.1, 7, 'One side is dead, the copper still sells.'],
      ['c9', 'Router Antenna', '📡', 0.2, 10, 'Snapped from an office router during teardown.'],
      ['c10', 'Pocket Calculator', '🧮', 0.2, 13, 'Sticky buttons, clean solar panel.'],
      ['c11', 'Alarm Clock Face', '⏰', 0.3, 8, 'Cheap plastic shell around a usable board.'],
      ['c12', 'Toaster Coil', '🔥', 0.4, 10, 'Nichrome coil with a little resale value.'],
      ['c13', 'Lamp Ballast', '💡', 0.6, 12, 'Buzzes faintly when power hits it.'],
      ['c14', 'Pager Shell', '📟', 0.2, 9, 'A relic shell with salvageable contacts.'],
      ['c15', 'Remote Control', '🎛️', 0.2, 8, 'Missing back cover, intact infrared diode.'],
      ['c16', 'Kiosk Keypad', '⌨️', 0.5, 14, 'Greasy fast-food terminal input pad.'],
      ['c17', 'VCR Head', '📼', 0.4, 12, 'Tiny mechanical assembly from a dead deck.'],
      ['c18', 'Printer Roller', '🖨️', 0.5, 11, 'Rubber feed roller from office surplus.'],
      ['c19', 'Desk Fan Motor', '🌀', 0.8, 15, 'Dusty motor that still spins when nudged.'],
      ['c20', 'Coffee Maker Thermostat', '☕', 0.2, 10, 'A small control part from a break-room machine.'],
      ['c21', 'Karaoke Mic Shell', '🎤', 0.3, 9, 'Cheap casing with a good connector ring.'],
      ['c22', 'CRT Button Panel', '📺', 0.4, 13, 'Front control strip from a curbside television.'],
      ['c23', 'Neon Sign Tube', '💈', 0.7, 14, 'Half-lit tubing from a dead pawnshop sign.'],
      ['c24', 'Set-Top Box Casing', '📦', 0.5, 11, 'Empty shell with a few reusable clips.'],
      ['c25', 'Copper Pipe Clamp', '🔩', 0.3, 9, 'Simple copper fastener from a burst wall line.'],
      ['c26', 'Steel Bolts', '🔩', 0.5, 8, 'Mixed hardware swept from a repair bay floor.'],
      ['c27', 'Bent Metal Tray', '🥣', 0.8, 11, 'Warped serving tray with recyclable metal.'],
      ['c28', 'Scrap Hinges', '🚪', 0.4, 9, 'Cabinet hinges with rust but good weight.'],
      ['c29', 'Brass Ring Blank', '💍', 0.1, 13, 'Unfinished ring form from a hobby kit.'],
      ['c30', 'Copper Mesh', '🧰', 0.2, 12, 'Fine copper weave from a broken vent cover.'],
      ['c31', 'Steel Chain Links', '⛓️', 0.7, 10, 'Short run of chain salvaged from a fence repair.'],
      ['c32', 'Scrap Rebar', '🏗️', 1.2, 12, 'Cut lengths of rebar from a demo pile.'],
      ['c33', 'Tin Ring Pulls', '🥫', 0.1, 6, 'A sack of can tabs sorted for weight.'],
      ['c34', 'Metal Drawer Rails', '🗄️', 0.9, 11, 'Greasy rails from a tossed filing cabinet.'],
      ['c35', 'Copper Heat Sink', '🧱', 0.6, 15, 'Compact sink block stripped from an old board.'],
      ['c36', 'Scrap Bracket', '🪝', 0.4, 8, 'Odd bracket that still adds up by the kilo.'],
      ['c37', 'Steel Washer Pack', '🧿', 0.2, 7, 'Loose washers bundled in a sandwich bag.'],
      ['c38', 'Metal Shelf Pegs', '📚', 0.1, 6, 'Tiny pegs from a broken retail display.'],
      ['c39', 'Copper Latch Plate', '🚪', 0.3, 10, 'Door hardware with solid copper backing.'],
      ['c40', 'Damaged Save Drive', '💾', 0.1, 16, 'Old flash drive labeled with forgotten backups.'],
      ['c41', 'Chip Socket Strip', '🧩', 0.1, 14, 'A tray of sockets from a hobby repair bench.'],
      ['c42', 'Transit Scanner Lens', '🔍', 0.2, 15, 'Cloudy scanner lens from a bus gate reader.'],
      ['c43', 'Crypto Receipt Drive', '💾', 0.1, 18, 'Contains transaction logs but not much else.'],
      ['c44', 'Wallet Recovery Card', '💳', 0.1, 17, 'Paper wallet backup card with partial keys.'],
      ['c45', 'AI Tutor Drive', '💽', 0.1, 19, 'School-issued learning drive with stale firmware.'],
      ['c46', 'Scooter Battery Casing', '🛴', 0.7, 14, 'Empty shell from a rental scooter battery.'],
      ['c47', 'Push Cart Wheel', '🛞', 0.9, 12, 'Solid rubber wheel from a busted market cart.'],
      ['c48', 'Moped Battery Harness', '🪫', 0.4, 15, 'Wiring loom from a stripped delivery moped.'],
      ['c49', 'Utility Cart Handle', '🛒', 0.8, 13, 'Powder-coated handlebar from a janitor cart.'],
      ['c50', 'Vehicle Mirror Shard', '🪞', 0.2, 11, 'Side mirror remains from a clipped sedan.'],
      ['c51', 'Delivery Cart Axle', '🛒', 1.1, 16, 'Short axle rod from a warehouse hand cart.'],
      ['c52', 'Forklift Battery Cap', '🔋', 0.2, 12, 'Heavy plastic cap from an industrial cell.'],
      ['c53', 'Service Cart Brake', '🛒', 0.6, 14, 'Wheel lock assembly from hospital surplus.'],
      ['c54', 'Vehicle Fuse Box', '🚗', 0.5, 16, 'Melted housing with a few good terminals.'],
      ['c55', 'Cargo Cart Strap', '🛒', 0.4, 10, 'Ratty restraint strap from a luggage cart.'],
    ]),
  ],
  uncommon: [
    { id: 'u1', name: 'Broken Smartphone', icon: '📱', rarity: 'uncommon', quantity: 1, weight: 0.3, value: 45, description: 'Cracked but salvageable.' },
    { id: 'u2', name: 'Fiber Optic Cable', icon: '🌐', rarity: 'uncommon', quantity: 1, weight: 0.8, value: 60, description: 'High-bandwidth cable.' },
    { id: 'u3', name: 'Vintage Radio', icon: '📻', rarity: 'uncommon', quantity: 1, weight: 1.5, value: 85, description: 'Pre-war era. Collectors love it.' },
    { id: 'u4', name: 'Silver Ring', icon: '💍', rarity: 'uncommon', quantity: 1, weight: 0.05, value: 75, description: 'Tarnished but real silver.' },
    { id: 'u5', name: 'Circuit Board', icon: '🔌', rarity: 'uncommon', quantity: 1, weight: 0.2, value: 50, description: 'From old computer.' },
    { id: 'cons_energy_drink', name: 'Energy Drink', icon: '⚡', rarity: 'uncommon', quantity: 1, weight: 0.3, value: 28, description: 'Strong boost. Restores 25 energy, +4 heat.' },
    { id: 'cons_medkit', name: 'Medkit', icon: '🩹', rarity: 'uncommon', quantity: 1, weight: 0.7, value: 45, description: 'Field treatment. Restores 18 energy, -12 heat.' },
    { id: 'eq_cart_u1', name: 'Old Shopping Cart', icon: '🛒', rarity: 'uncommon', quantity: 1, weight: 8.0, value: 120, description: 'Dented but sturdy. +10% capacity.' },
    { id: 'eq_pack_u1', name: 'Weathered Backpack', icon: '🎒', rarity: 'uncommon', quantity: 1, weight: 2.5, value: 95, description: 'Torn straps. +8% search speed.' },
    { id: 'eq_light_u1', name: 'LED Flashlight', icon: '🔦', rarity: 'uncommon', quantity: 1, weight: 0.3, value: 80, description: 'Decent battery. -3% heat gain.' },
    { id: 'eq_glove_u1', name: 'Work Gloves', icon: '🧤', rarity: 'uncommon', quantity: 1, weight: 0.2, value: 70, description: 'Worn leather. +2% rarity chance.' },
    ...createLootItems('uncommon', [
      ['u6', 'Refurbished Tablet', '📱', 0.5, 74, 'Still boots into a cracked school login screen.'],
      ['u7', 'Drone Camera Mount', '📷', 0.4, 68, 'Gimbal bracket from a hobby drone crash.'],
      ['u8', 'Office Projector Lens', '📽️', 0.6, 82, 'Dusty glass tube from a conference room cleanup.'],
      ['u9', 'Smart Thermostat Core', '🌡️', 0.3, 78, 'Wi-Fi control board from a smart home retrofit.'],
      ['u10', 'Arcade Button Board', '🕹️', 0.5, 71, 'Button matrix from a dead cabinet door.'],
      ['u11', 'Signal Booster', '📶', 0.4, 76, 'Handmade booster stripped from a rooftop mast.'],
      ['u12', 'Portable DVD Lens', '💿', 0.2, 63, 'Surprisingly clean pickup lens assembly.'],
      ['u13', 'Studio Headphones', '🎧', 0.4, 79, 'One ear dead, housing and drivers still useful.'],
      ['u14', 'Security Monitor Panel', '📺', 0.7, 88, 'LCD panel from a cracked surveillance monitor.'],
      ['u15', 'Solar Garden Light', '🔆', 0.3, 59, 'Cheap solar cap with a reusable charge board.'],
      ['u16', 'Diagnostic Multimeter', '📏', 0.4, 83, 'Scuffed casing, solid probes, partial readout.'],
      ['u17', 'Barcode Printer Head', '🖨️', 0.3, 80, 'Thermal head from a warehouse label printer.'],
      ['u18', 'Sterling Ring Setting', '💍', 0.1, 91, 'Unset silver ring frame from a craft booth clearout.'],
      ['u19', 'Copper Bus Bar', '🟧', 0.7, 86, 'Heavy conductive strip from industrial cabinets.'],
      ['u20', 'Steel Cable Reel', '🧵', 1.2, 88, 'Partial reel of braided steel utility line.'],
      ['u21', 'Scrap Bronze Valve', '🚰', 0.8, 84, 'Bronze plumbing valve with good salvage weight.'],
      ['u22', 'Alloy Tool Chest', '🧰', 1.6, 95, 'Dented chest with a surprisingly clean alloy shell.'],
      ['u23', 'Metal Case Lock', '🔒', 0.3, 73, 'Stout lock body with intact tumbler pins.'],
      ['u24', 'Copper Compressor Coil', '🌀', 0.9, 98, 'Warm copper windings cut from a dead fridge.'],
      ['u25', 'Steel Plate Bundle', '📚', 1.4, 90, 'Stack of trimmed plates from a fab shop bin.'],
      ['u26', 'Chrome Ring Band', '💍', 0.1, 87, 'Bright ring blank from an abandoned market stall.'],
      ['u27', 'Scrap Rail Segment', '🚆', 1.8, 92, 'Short rail offcut from track maintenance.'],
      ['u28', 'Metal Sink Faucet', '🚿', 0.9, 81, 'Brushed faucet head with solid brass undercoat.'],
      ['u29', 'Encrypted Backup Drive', '💾', 0.1, 102, 'Business backups sit behind an old password prompt.'],
      ['u30', 'Campus AI Assistant', '🤖', 0.2, 110, 'Dorm-room helper node with canned tutoring routines.'],
      ['u31', 'Mapping Scanner Wand', '🔍', 0.3, 106, 'Maintenance wand used to map utility tunnels.'],
      ['u32', 'Wallet Sync Dongle', '💳', 0.1, 108, 'Offline wallet bridge for cheap point-of-sale rigs.'],
      ['u33', 'Server Chip Rack', '🧩', 0.2, 112, 'Tray of matched chips from a recycled blade server.'],
      ['u34', 'Patch Archive Drive', '💽', 0.1, 104, 'Labeled with legacy firmware bundles.'],
      ['u35', 'Train Scanner Head', '🚉', 0.4, 111, 'Optical scanner head from a platform ticket gate.'],
      ['u36', 'AI Helpdesk Node', '🤖', 0.3, 115, 'Small office kiosk brain built for canned support chats.'],
      ['u37', 'Crypto Mining Drive', '💾', 0.2, 118, 'Drive packed with stale mining software and logs.'],
      ['u38', 'Access Chip Carousel', '🎠', 0.2, 109, 'Rotating chip feeder from a secure print room.'],
      ['u39', 'Tram Battery Pack', '🔋', 1.2, 124, 'Compact transit battery module with scrapable cells.'],
      ['u40', 'Folding Cart Frame', '🛒', 1.6, 127, 'Collapsed street cart frame from a market sweep.'],
      ['u41', 'Courier Cart Basket', '🧺', 1.1, 121, 'Wire basket sized for rush-hour parcel runs.'],
      ['u42', 'Scooter Battery Array', '🔋', 0.9, 129, 'Cluster of commuter scooter cells, mostly drained.'],
      ['u43', 'Vehicle Dash Cluster', '🚗', 0.7, 123, 'Instrument cluster pulled from a taxi graveyard.'],
      ['u44', 'Utility Vehicle Seat', '🪑', 2.1, 116, 'Vinyl bench seat with intact slide rails.'],
      ['u45', 'Service Cart Motor', '🛒', 1.4, 133, 'Compact motor from a hospital transport cart.'],
      ['u46', 'Compact Exoskeleton Brace', '🦿', 1.0, 136, 'Assist brace from a discontinued warehouse rig.'],
      ['u47', 'Bike Battery Rail', '🔋', 0.8, 122, 'Mounting rail for a commuter e-bike battery.'],
      ['u48', 'Delivery Cart Wheelset', '🛞', 1.3, 120, 'Matched pair of wheels from a food-run cart.'],
      ['u49', 'Harbor Vehicle Beacon', '⚓', 0.5, 118, 'Dock safety beacon off a yard vehicle roof.'],
      ['u50', 'Moped Cart Coupler', '🛒', 0.6, 117, 'Weird hitch assembly from a courier custom job.'],
    ]),
  ],
  rare: [
    { id: 'r1', name: 'Old GPU', icon: '🖥️', rarity: 'rare', quantity: 1, weight: 1.2, value: 320, description: 'GTX 1080 class.' },
    { id: 'r2', name: 'Prototype Battery', icon: '🔋', rarity: 'rare', quantity: 1, weight: 0.6, value: 450, description: 'Next-gen solid-state.' },
    { id: 'r3', name: 'Gold Ring', icon: '💍', rarity: 'rare', quantity: 1, weight: 0.05, value: 400, description: '18k solid gold.' },
    { id: 'r4', name: 'Vintage Watch', icon: '⌚', rarity: 'rare', quantity: 1, weight: 0.2, value: 380, description: 'Swiss mechanics still work.' },
    { id: 'r5', name: 'Lab Equipment', icon: '🔬', rarity: 'rare', quantity: 1, weight: 2.0, value: 500, description: 'Precision instrument.' },
    { id: 'eq_cart_r1', name: 'Industrial Dolly', icon: '🛒', rarity: 'rare', quantity: 1, weight: 12.0, value: 580, description: 'Heavy-duty warehouse model. +25% capacity.' },
    { id: 'eq_pack_r1', name: 'Military Backpack', icon: '🎒', rarity: 'rare', quantity: 1, weight: 3.0, value: 420, description: 'Kevlar-reinforced. +18% search speed.' },
    { id: 'eq_light_r1', name: 'Xenon Torch', icon: '🔦', rarity: 'rare', quantity: 1, weight: 0.5, value: 380, description: 'Powerful beam. -8% heat gain.' },
    { id: 'eq_glove_r1', name: 'Leather Grip Gloves', icon: '🧤', rarity: 'rare', quantity: 1, weight: 0.3, value: 320, description: 'Professional-grade. +6% rarity chance.' },
    ...createLootItems('rare', [
      ['r6', 'Rugged Tablet', '📱', 0.8, 540, 'Field tablet from a demolition contractor fleet.'],
      ['r7', 'Stereo Receiver Core', '📻', 1.1, 520, 'Heavy audio receiver with intact copper sinks.'],
      ['r8', 'Cinema Projector Lamp', '📽️', 0.4, 505, 'High-brightness lamp pack from a shuttered theater.'],
      ['r9', 'Emergency Beacon', '🚨', 0.6, 560, 'Maritime beacon housing with a clean strobe board.'],
      ['r10', 'Smart Lock Kit', '🔐', 0.5, 545, 'Networked lock assembly from a condo remodel.'],
      ['r11', 'Recon Drone Shell', '🛸', 0.7, 590, 'Composite shell with mount points still intact.'],
      ['r12', 'Industrial Oscilloscope', '📈', 1.5, 610, 'Bench scope from a lab liquidation lot.'],
      ['r13', 'Laser Pointer Module', '🔴', 0.2, 490, 'Precision module used in alignment rigs.'],
      ['r14', 'Weather Station Console', '🌦️', 0.9, 570, 'Data console from a university rooftop station.'],
      ['r15', 'Portable Sonar Unit', '📡', 1.0, 620, 'Harbor sonar unit with a battered waterproof shell.'],
      ['r16', 'Gold Ring Setting', '💍', 0.1, 680, 'Empty gold setting ready for a replacement stone.'],
      ['r17', 'Titanium Scrap Bundle', '🧱', 1.0, 710, 'Cutoffs from aerospace-grade panel stock.'],
      ['r18', 'Copper Cooling Manifold', '🌀', 0.9, 690, 'Complex cooling manifold from an industrial chiller.'],
      ['r19', 'Steel Safe Handle', '🗝️', 0.8, 640, 'Chunky safe hardware with weight to spare.'],
      ['r20', 'Diamond Dust Vial', '💎', 0.1, 760, 'Micron diamond dust from a precision workshop.'],
      ['r21', 'Metal Forge Tongs', '🔥', 1.1, 605, 'Specialty tongs forged from quality metal stock.'],
      ['r22', 'Scrap Turbine Blade', '🛩️', 1.3, 785, 'Nickel alloy blade with a scorched root edge.'],
      ['r23', 'Platinum Ring Blank', '💍', 0.1, 735, 'Dense ring blank with mirror-polished edges.'],
      ['r24', 'Steel Crane Hook', '🏗️', 1.7, 720, 'Forged hook retired from dockside service.'],
      ['r25', 'Copper Relay Block', '🧲', 0.6, 655, 'Machined copper block from a power relay array.'],
      ['r26', 'Neural Net Drive', '💾', 0.2, 820, 'Dev drive loaded with abandoned machine-learning weights.'],
      ['r27', 'Forensic Scanner', '🔍', 0.5, 880, 'Portable unit built to read damaged tags and IDs.'],
      ['r28', 'Quantum Chip Carrier', '🧩', 0.2, 915, 'Shielded transport rack for fragile research chips.'],
      ['r29', 'AI Router Brain', '🤖', 0.3, 860, 'Self-tuning network brain from a smart building core.'],
      ['r30', 'Wallet Seed Drive', '💽', 0.1, 895, 'Contains fragments of an early cold-wallet backup.'],
      ['r31', 'Fraud Scanner Module', '🔎', 0.4, 840, 'Bank counter scanner trained on counterfeit markers.'],
      ['r32', 'Cloud Backup Drive', '💾', 0.2, 810, 'Enterprise backup drive with intact encrypted partitions.'],
      ['r33', 'Robotics Chip Stack', '🧩', 0.2, 905, 'Matched chips from a decommissioned warehouse arm.'],
      ['r34', 'Crypto Ledger Drive', '💽', 0.1, 940, 'Cold ledger storage from a failed trading desk.'],
      ['r35', 'AI Translation Core', '🤖', 0.3, 870, 'Real-time language core from a customs terminal.'],
      ['r36', 'Fleet Battery Module', '🔋', 1.1, 980, 'High-cycle battery pulled from a delivery fleet.'],
      ['r37', 'Utility Cart Suspension', '🛒', 1.4, 930, 'Custom suspension arms from a heavy service cart.'],
      ['r38', 'Vehicle ECU Crate', '🚗', 0.9, 990, 'Crate of vehicle control modules from an impound auction.'],
      ['r39', 'Salvage Exoskeleton Joint', '🦿', 1.2, 1040, 'Servo joint from a loader exoskeleton rig.'],
      ['r40', 'Racing Cart Fork', '🛒', 1.0, 910, 'Front fork from an illegal alley racing cart.'],
      ['r41', 'Hybrid Battery Block', '🔋', 1.3, 1060, 'Dense energy block stripped from a taxi hybrid.'],
      ['r42', 'Vehicle Sensor Mast', '🚘', 0.8, 965, 'Roof-mounted sensor mast from an autonomous test car.'],
      ['r43', 'Cargo Cart Lift', '🛒', 1.6, 1005, 'Compact lift assembly from a warehouse tug cart.'],
      ['r44', 'Patrol Vehicle Console', '🚓', 1.0, 1015, 'Dashboard console from an auctioned fleet unit.'],
      ['r45', 'Rescue Cart Winch', '🛒', 1.5, 950, 'Winch drum from an old rescue support cart.'],
    ]),
  ],
  epic: [
    { id: 'e1', name: 'Crypto Wallet Drive', icon: '💾', rarity: 'epic', quantity: 1, weight: 0.1, value: 1200, description: 'Encrypted digital assets.' },
    { id: 'e2', name: 'Biometric Scanner', icon: '👁️', rarity: 'epic', quantity: 1, weight: 0.4, value: 2100, description: 'Ripped from facility.' },
    { id: 'e3', name: 'Rare Diamond', icon: '💎', rarity: 'epic', quantity: 1, weight: 0.05, value: 3500, description: '5 carat, flawless.' },
    { id: 'e4', name: 'Vintage Rolex', icon: '⌚', rarity: 'epic', quantity: 1, weight: 0.2, value: 4200, description: '1960s model, pristine.' },
    { id: 'e5', name: 'AI Core Module', icon: '🤖', rarity: 'epic', quantity: 1, weight: 0.5, value: 5500, description: 'Quantum processor.' },
    { id: 'eq_cart_e1', name: 'Hover Cart', icon: '🛒', rarity: 'epic', quantity: 1, weight: 6.0, value: 2800, description: 'Anti-gravity prototype. +40% capacity, -5% heat.' },
    { id: 'eq_pack_e1', name: 'Nano-Fiber Satchel', icon: '🎒', rarity: 'epic', quantity: 1, weight: 1.5, value: 2100, description: 'Synthetic fibers. +28% search speed.' },
    { id: 'eq_light_e1', name: 'Plasma Flare', icon: '🔦', rarity: 'epic', quantity: 1, weight: 0.6, value: 1800, description: 'Generates light. -15% heat gain.' },
    { id: 'eq_glove_e1', name: 'Neural Response Gloves', icon: '🧤', rarity: 'epic', quantity: 1, weight: 0.4, value: 1600, description: 'Enhanced grip. +12% rarity chance.' },
    ...createLootItems('epic', [
      ['e6', 'Hologram Projector', '🛰️', 0.7, 6400, 'Retail-grade projector repurposed for pop-up scams.'],
      ['e7', 'Satellite Phone Cluster', '📞', 0.8, 5900, 'Bundle of hardened comms handsets from a shipping lot.'],
      ['e8', 'Quantum Speaker Array', '🔊', 0.6, 6200, 'Prototype audio rig with impossible clarity.'],
      ['e9', 'Drone Swarm Hub', '🛸', 0.9, 6700, 'Control hub that once coordinated a dozen service drones.'],
      ['e10', 'Medical Imaging Wand', '🩺', 0.5, 6100, 'Portable scanner wand from a luxury clinic closure.'],
      ['e11', 'Precision Lidar Lens', '🔭', 0.4, 6550, 'High-end lens assembly from survey equipment.'],
      ['e12', 'Cryo Sensor Pod', '🧊', 0.7, 6050, 'Environmental sensor pod from biotech shipping.'],
      ['e13', 'Vault Alarm Matrix', '🚨', 0.6, 6900, 'Multi-zone alarm brain from a cracked private vault.'],
      ['e14', 'Platinum Ring Trio', '💍', 0.1, 7600, 'Matched platinum bands wrapped in velvet dust.'],
      ['e15', 'Diamond Relay Crown', '💎', 0.2, 8200, 'Diamond-set relay housing from a ceremonial comms piece.'],
      ['e16', 'Osmium Scrap Capsule', '🧪', 0.5, 7800, 'Dense capsule of osmium offcuts from a lab auction.'],
      ['e17', 'Gold Thread Spool', '🧵', 0.3, 7400, 'Conductive gold filament spool from couture robotics work.'],
      ['e18', 'Meteoric Metal Slab', '🪨', 1.2, 8500, 'A cut slab of unusually patterned meteoric metal.'],
      ['e19', 'Copper Quantum Coil', '🌀', 0.7, 7700, 'Coil wound for an abandoned quantum cooling rig.'],
      ['e20', 'Diamond Prism Cage', '💎', 0.3, 8100, 'Optical cage using diamond-cut prism supports.'],
      ['e21', 'Blackbox AI Core', '🤖', 0.4, 9300, 'Opaque machine-learning core from a failed startup lab.'],
      ['e22', 'Cold Wallet Drive', '💾', 0.1, 10100, 'Air-gapped wallet drive hidden in a false battery shell.'],
      ['e23', 'Threat Scanner Cluster', '🔍', 0.5, 9500, 'Security scanner cluster built for executive checkpoints.'],
      ['e24', 'Predictive Chip Lattice', '🧩', 0.3, 9800, 'Chip lattice tuned for predictive logistics models.'],
      ['e25', 'Ghost Archive Drive', '💽', 0.1, 9700, 'Wiped archive drive that still leaks metadata traces.'],
      ['e26', 'Autonomous AI Broker', '🤖', 0.4, 10400, 'Trading AI node abandoned after a regulatory freeze.'],
      ['e27', 'Crypto Vault Drive', '💾', 0.2, 11000, 'Triple-encrypted vault drive with tamper scoring.'],
      ['e28', 'Deep Scanner Prism', '🔎', 0.3, 9900, 'Spectral scanner prism from a customs black room.'],
      ['e29', 'Tactical Battery Stack', '🔋', 1.0, 8600, 'Stacked field batteries from a private security truck.'],
      ['e30', 'Hover Cart Gyro', '🛒', 1.1, 8900, 'Stabilizer gyro from a prototype hovering cargo cart.'],
      ['e31', 'Rescue Vehicle Nav', '🚑', 0.8, 8450, 'Navigation brain from a retired emergency vehicle.'],
      ['e32', 'Industrial Exoskeleton Spine', '🦴', 1.6, 9800, 'Powered spine rail from a heavy-lift exoskeleton.'],
      ['e33', 'Courier Cart Thrusters', '🛒', 1.0, 9100, 'Short-burst thruster pods from a banned courier mod.'],
      ['e34', 'Silent Vehicle Rotors', '🚁', 0.9, 8750, 'Low-noise rotor set from a stealthy yard vehicle.'],
      ['e35', 'Smuggler Battery Rack', '🔋', 1.2, 9400, 'Dense rack of contraband high-discharge cells.'],
    ]),
  ],
  legendary: [
    { id: 'l1', name: 'Military Chip', icon: '🔬', rarity: 'legendary', quantity: 1, weight: 0.05, value: 8500, description: 'Unknown prototype.' },
    { id: 'l2', name: 'Crown Jewels', icon: '👑', rarity: 'legendary', quantity: 1, weight: 0.1, value: 15000, description: 'Historical artifact.' },
    { id: 'l3', name: 'Original Bitcoin Wallet', icon: '💰', rarity: 'legendary', quantity: 1, weight: 0.05, value: 50000, description: 'Contains fortune.' },
    { id: 'l4', name: 'Ancient Artifact', icon: '🏺', rarity: 'legendary', quantity: 1, weight: 1.0, value: 12000, description: 'Museum-worthy.' },
    { id: 'l5', name: 'Experimental Exoskeleton', icon: '🤖', rarity: 'legendary', quantity: 1, weight: 8.0, value: 25000, description: 'Military grade.' },
    ...createLootItems('legendary', [
      ['l6', 'Orbital Beacon Array', '🛰️', 0.8, 14800, 'Satellite beacon cluster salvaged from a black-budget crate.'],
      ['l7', 'Prototype City Grid Lens', '🔭', 0.6, 15600, 'Optical relay lens designed for smart-grid oversight.'],
      ['l8', 'Zero-Latency Radar Halo', '📡', 0.9, 16200, 'Rare radar ring with military-grade shielding.'],
      ['l9', 'Cognitive Jammer Relay', '🧠', 0.7, 17100, 'Interference relay built to blind autonomous patrols.'],
      ['l10', 'Vaultbreaker Sonic Loom', '🔊', 1.0, 18500, 'Compact sonic lattice used in elite breach drills.'],
      ['l11', 'Royal Diamond Band', '💍', 0.1, 19200, 'Diamond-studded ring band from a private estate purge.'],
      ['l12', 'Sunfire Metal Heart', '☀️', 0.8, 20400, 'Experimental reactor core built around rare metal plates.'],
      ['l13', 'Celestial Copper Core', '🟧', 0.6, 18800, 'Pure copper core used in a boutique fusion mock-up.'],
      ['l14', 'Kingsguard Ring Matrix', '💍', 0.2, 21600, 'Ceremonial ring array wired into an old security vault.'],
      ['l15', 'Mythic Scrap Ingot', '🧱', 1.4, 19800, 'Dense ingot forged from mixed legendary scrap feeds.'],
      ['l16', 'Sovereign AI Lattice', '🤖', 0.4, 23500, 'Elite AI compute lattice from a dead sovereign cloud node.'],
      ['l17', 'Genesis Wallet Drive', '💾', 0.1, 26400, 'Wallet drive rumored to predate the first market fork.'],
      ['l18', 'Crown Scanner Halo', '👑', 0.3, 24100, 'Scanner ring built for artifact authentication at court auctions.'],
      ['l19', 'Omega Chip Archive', '🧩', 0.2, 25200, 'One-of-a-kind archive of unreleased processor dies.'],
      ['l20', 'Ghostmind AI Prism', '🔮', 0.3, 27900, 'Prism-like AI core with impossible inference speed.'],
      ['l21', 'Titan Battery Spine', '🔋', 1.7, 22100, 'Backbone battery from a siege-grade loader frame.'],
      ['l22', 'Phantom Cart Engine', '🛒', 1.5, 23800, 'Silent-drive engine once fitted to a covert cargo cart.'],
      ['l23', 'Apex Vehicle Helm', '🚘', 1.0, 24700, 'Control helm from a prototype autonomous vehicle platform.'],
      ['l24', 'Dominion Exoskeleton Frame', '🦿', 2.2, 28600, 'Command frame from a decommissioned corporate exoskeleton.'],
      ['l25', 'Royal Cart Throne', '🛒', 1.3, 23100, 'Absurd custom seat built for a collector-grade parade cart.'],
      ['l26', 'Legendary Keyboard', '⌨️', 0.7, 16800, 'Collector-grade keyboard built with impossible switches and a one-off chassis.'],
    ]),
  ],
  illegal: [
    { id: 'il1', name: 'Stolen Keycard', icon: '💳', rarity: 'illegal', quantity: 1, weight: 0.05, value: 3000, description: 'Corporate access. Illegal to possess.' },
    { id: 'il2', name: 'Counterfeit Money', icon: '💵', rarity: 'illegal', quantity: 1, weight: 0.2, value: 5000, description: 'Very convincing.' },
    { id: 'il3', name: 'Classified Docs', icon: '📄', rarity: 'illegal', quantity: 1, weight: 0.1, value: 7500, description: 'Government secrets.' },
    { id: 'il4', name: 'Smuggled Diamonds', icon: '💎', rarity: 'illegal', quantity: 1, weight: 0.05, value: 12000, description: 'Black market haul.' },
    { id: 'il5', name: 'Nuclear Material', icon: '☢️', rarity: 'illegal', quantity: 1, weight: 2.0, value: 20000, description: 'EXTREMELY dangerous.' },
    ...createLootItems('illegal', [
      ['il6', 'Blackmail Wallet Drive', '💾', 0.1, 9200, 'Wallet drive loaded with extortion payments and names.'],
      ['il7', 'Forged Keycard Suite', '💳', 0.1, 9800, 'Batch of cloned access cards for a private tower.'],
      ['il8', 'Phantom Counterfeit Plate', '💵', 0.4, 10400, 'Print plate used for boutique counterfeit runs.'],
      ['il9', 'State Classified Ledger', '📄', 0.2, 11800, 'Hardcopy ledger from a sealed procurement office.'],
      ['il10', 'Smuggled Diamond Parcel', '💎', 0.1, 13300, 'Loose stones wrapped in customs-bypassing tape.'],
      ['il11', 'Dirty Crypto Wallet', '💾', 0.1, 12100, 'Wallet drive tied to frozen laundering routes.'],
      ['il12', 'Silent Keycard Printer', '🖨️', 1.1, 14500, 'Compact printer tuned for off-book access badges.'],
      ['il13', 'Counterfeit Bond Roll', '💵', 0.3, 12600, 'Rolled bonds designed to pass a quick audit glance.'],
      ['il14', 'Classified Drone Tape', '📼', 0.2, 15100, 'Storage media from a surveillance drone program.'],
      ['il15', 'Ghost Passport Stack', '🛂', 0.2, 11200, 'Fresh identity set hidden in a courier satchel liner.'],
      ['il16', 'Smuggled Battery Serum', '🔋', 0.6, 16400, 'Illegal cell enhancer banned after multiple fires.'],
      ['il17', 'Blacksite Scanner Key', '🔑', 0.1, 17600, 'Scanner auth key for an unlisted detention site.'],
      ['il18', 'Counterfeit Chip Stamp', '🧩', 0.2, 13900, 'Forgery stamp used to fake premium processor markings.'],
      ['il19', 'Classified Exoskeleton Map', '🗺️', 0.2, 18300, 'Blueprint routes for moving covert exoskeleton shipments.'],
      ['il20', 'Smuggled Uranium Ring', '💍', 0.2, 19800, 'Shielded ring canister moving hot material in plain sight.'],
    ]),
  ],
};

export const MARKET_SOURCE_ITEMS = Object.values(LOOT_TEMPLATES).flat();
